### ISSUE TITLE
Very low entropy of code word and short english only word list.

### ISSUE THREAD

**Issue by therealraven** [magic-wormhole/magic-wormhole#301]
I notice that the word list is only 512 words.

This leaves log2(512^2)=18 bits of entropy for the use of 2 code words. Really it is **16 bits** since words must alternate between even and odd for error detection.

Using a larger 2048 word list from the standard [BIP39 word lists](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md) is an easy way to greatly increase this entropy, while adding multi-language support.

Due to the use of nameplates the chance of collision is low, but not the usual cryptographically-secure-astronomical-scale-chance-of-happening type of low that I would have expected.

- Without using the even-odd error detection this would increase 2 word entropy to **22 bits**, up from the current 16 bits. 

- It would be **33 bits with 3 words**.

- The [BIP39 word lists](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md) also have support for **various languages** other than english.

- These word lists are carefully selected so that **3 characters uniquely identifies every word**, which is useful for auto completion.

**Comment by meejah** [comment]
While there may be good reasons to use other word-lists, the "lack of entropy" isn't an issue; see for example https://github.com/magic-wormhole/magic-wormhole/issues/359 or https://github.com/magic-wormhole/magic-wormhole/issues/191

For the internationalization / non-english aspect, please see https://github.com/magic-wormhole/magic-wormhole-protocols/issues/31
