### ISSUE TITLE
Document WORMHOLE_RELAY_URL environment variable

### ISSUE THREAD

**Issue by rixx** [magic-wormhole/magic-wormhole#338]
For the CLI, you can specify the relay server via the WORMHOLE_RELAY_URL variable. It would be great to mention this – especially when rolling your own server, you'll want to avoid typing it out every time you invoke wormhole.

**Comment by warner** [comment]
Good idea. Maybe this should go into the man page (`docs/wormhole.1`)?

**Comment by kimusan** [comment]
Would be even better if it could be configured via a .wormholerc or similar config file.

**Comment by warner** [comment]
Does anyone have a favorite dotfile-handling library? Or even just an opinion over where it should live? I see a lot of stuff in my `~/.config/` directory, so I wonder if `~/.config/wormhole` might fit within some sort of XDG standard or something. I suppose we should use a standard .ini format, so we can stick with the `configparser.ConfigParser` from python's stdlib, and not add any new dependencies.

**Comment by rixx** [comment]
> I see a lot of stuff in my `~/.config/` directory, so I wonder if `~/.config/wormhole` might fit within some sort of XDG standard or something.

`~/.config` is the default value of `XDG_CONFIG_HOME`, so that would be a good pattern to follow. See also: the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

> I suppose we should use a standard .ini format, so we can stick with the `configparser.ConfigParser` from python's stdlib, and not add any new dependencies.

In my experience, `configparser` is good enough for all non-complex configuration.

**Comment by kschulz-samsung** [comment]
I agree. .config/wormhole would be a good place. I have used the configParser previously and that one is actually handling even quite advanced configs (way more than wormhole would ever need)

**Comment by sunknudsen** [comment]
Stumbled upon this thread looking for a permanent way to set relay URL and transit helper.

I agree adding `WORMHOLE_RELAY_URL` and `WORMHOLE_TRANSIT_HELPER` to docs would be useful (looks like these environment variables have not been mentioned in the docs to this day).

I also like the `~/.config` idea. Borg and Wireshark use that folder on macOS.

**Comment by j-lakeman** [comment]
Hey, just came across this. Is this documented somewhere within the application? Neither could find it in the man page nor though `--help`.

**Comment by meejah** [comment]
Hmm, I agree it doesn't should up very nicely; filed https://github.com/magic-wormhole/magic-wormhole/issues/609
