### ISSUE TITLE
Security Concerns

### ISSUE THREAD

**Issue by PowerPress** [magic-wormhole/magic-wormhole#359]
Please see this discussion on crypto @ reddit https://old.reddit.com/r/crypto/comments/d6f0t5/does_magicwormhole_look_reasonably_safe/

A glaring issue is the password used, please look into this.

**Comment by meejah** [comment]
This is a good paper to read: https://www.di.ens.fr/~mabdalla/papers/AbPo05a-letter.pdf

An attacker only gets one guess, so a low-entropy secret is fine here as I understand it.

**Comment by warner** [comment]
@PowerPress, thanks for the heads-up. I think there's a lot of misunderstanding about what PAKE does and does not offer, and I need to write up an explanation that we can point to when folks get concerned about the short wormhole code (and why it doesn't create the same vulnerability as a short password).

**Comment by LogikerKit** [comment]
But what about a malicious or compromised rendezvous server? So if the rendezvous server would only try to guess every 1000th connection and there are enough users then this might not raise suspicion. So a successful non-user-specific attack on all magic wormhole connections is I think still feasible with this low password entropy.

**Comment by warner** [comment]
@LogikerKit yeah, that sort of slow/under-the-radar attack is definitely possible. Fortunately it's the the best attack that a compromised server could mount, I think.

Huh, now I'm curious about what attack/success rate might actually be feasible. From my logs, over the last 12-ish months, there have been 118200 successful ("happy") connections through the mailbox server, and 4280 "scary" ones (where at least one side reported a PAKE key mismatch, which is either a failed attack, or just somebody making a typo when they entered the code). There were also about 37k "pruney" events, where one side connected but the other never showed up.

Let's assume the worst case: somebody has been running an under-the-radar attack for the entire year, and nobody has ever made a typo while entering the code. So every one of those 4280 "scary" events is really a failed attack. The 118k "happy" events are either actual successes (no attack was attempted), or successful attacks.

If most everybody is using the default 16-bit code (two words, each from a 256-entry list), then those 4280 failures represent 65535/65536 of the attempted attacks. Their chances of success are uniformly random, which means they had roughly a 4280/65536 = 6.5% chance of making one successful attack over the course of the last year.

When I was doing this sort of math for Firefox Sync (back in the J-PAKE days, which inspired magic-wormhole), I figured we could watch the server for errors, and tune the code length to target some "maximum rate of successful attack" threshold. For example, maybe we say we want a lower than one-in-a-million chance of anybody's connections getting successfully attacked each year. No matter how many attackers there are, we want to keep their total average success rate to somewhere below one per million years. How could we do this?

We would watch the reported failure rate, divide by the number of possible codes, and adjust the code length to keep that value below the target. For magic-wormhole, the last year's reported failure rate is 4280 per year, and the number of possible codes is 65536. The resulting rate is 0.065 successful attacks per year, or about one successful attack per 15 years. To achieve a one-in-a-million-years target, we should be using 1e6/15 = 65037 times as many codes, which means an additional `ln2(65037)` bits, which is nearly 16. So a four-word code would let us meet the (somewhat overzealous, I must admit) one-in-a-million-years target.

If the total traffic rate goes up, the attacker has more places to hide. If, as I believe, almost all of those 4280 failures were indeed typos, then if we'd had ten times as many attempted connections, I think we'd have ten times as many failures. But we can't tell the difference between typos and failed attacks. So if we saw 42800 failures in a year, we would pessimistically assume that they were all failed attacks. And with 16-bit codes, that increases our hypothetical attacker's rate to 65% during that year (an average of one success every 18 months). That would be a high enough rate that I'd probably want to increase the defaults to use three words.

But, if we assume that the server hasn't been under attack all this time (and you assume that I'm telling the truth about the logs, of course), then we've basically established a (4280 / 4280+118200) = 3.5% rate of typos. We could watch the server for *more* failures than that background rate, and treat those as attacks, and do the math to adjust the code length to stay above whatever threshold we picked. We might also pay attention to UX changes: maybe using a different word list would result in fewer typos? Or a different way to enter the code, or a different way to express the code entirely. I think that once we implement localized wordlists, we might want to track success/failure rates separately by language (if the server is allowed to see that, but to make tab-completion useful the choice of wordlist must be visible in cleartext), to see if we need to adjust the way wordlists work somehow.

Anyways, yeah, if an attacker goes slow, they can be hard to detect, but their success rate goes way down. And it's super easy to make the code longer at the first signs of trouble. I'm hoping the ease of reactive defense will discourage a potential attacker from bothering.

**Comment by warner** [comment]
I think we've explored this enough for now, so I'm going to close it. I think the action item might be to make sure this explanation is easy to find. https://github.com/magic-wormhole/magic-wormhole/blob/master/docs/attacks.md has a basic writeup, but we've gone into more depth here and elsewhere, and it might be nice to have a single place to point future "OMG short password" concerns at. We might actually need a whole page just to give folks a place to learn about PAKE and why the short password isn't the problem they might think it is.
