### ISSUE TITLE
MacOS Catalina Installation Error

### ISSUE THREAD

**Issue by joshuaquek** [magic-wormhole/magic-wormhole#389]
Got this error when trying to install using Homebrew:

```bash
==> Pouring magic-wormhole-0.12.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/magic-wormhole/0.12.0: 2,531 files, 35MB
==> `brew cleanup` has not been run in 30 days, running now...
Error: Permission denied @ apply2files - /usr/local/share/ghostscript/9.19/Resource/CIDFSubst/ipaexg.ttf
```
Any fixes?

**Comment by dsedivec** [comment]
I a betting this error is unrelated to magic-wormhole.  Do you get this same error if you run `brew cleanup` by itself?

**Comment by smammy** [comment]
This issue should be closed.

@joshuaquek, you are experiencing a Homebrew issue. See: Homebrew/homebrew-core#45009

**Comment by warner** [comment]
closing as a homebrew thing
