### ISSUE TITLE
Add to Chocolatey repository

### ISSUE THREAD

**Issue by aquacash5** [magic-wormhole/magic-wormhole#397]
I am an avid user on windows. Currently, I use pipx to install magic-wormhole, but would love to consolidate down to just Chocolatey. I would love to help get magic-wormhole into Chocolatey in any way I can.

[Creating a Chocolatey package](https://chocolatey.org/docs/create-packages)

**Comment by vaporwave9** [comment]
Has there been any progress? I can live with pipx but acceptance among friends and family is limited. They don't like MSBuildTools and running a whole toolchain, at all.

What kept me from building a windows binary only were the issue of relative paths.
https://github.com/magic-wormhole/magic-wormhole/issues/360
https://github.com/pyinstaller/pyinstaller/issues/2560#issuecomment-777257579

I can perfectly compile a single binary, which will simply not run. Despite fixing all relative paths in every python script. In the end I gave up. If the other people working on this have ever yielded an executable that is portable is unknown.

**Comment by aquacash5** [comment]
@vaporwave9 after reading your comment, I took a stab at using `pyinstaller` to create an executable.

It may be a little unorthodox, but I got it to work. https://github.com/aquacash5/magic-wormhole-exe

Now, all we need is to write the Chocolatey packaging script.

**Comment by vaporwave9** [comment]
Many thanks! I can try this once at home in around 12 hours, reading the Chocolatey docs again for now. What kept me so far was that I need to test it somehow without publishing and lack of time to maintain it.

This seems straight forward fow now, we have your self contained binary:

’’’
If you have a self-contained package, you can remove the automation scripts entirely and just include the runtime executables, they will automatically get shimmed, which puts them on the path. 
’’’
By creating an always valid URL for your build artifacts we ensure it never is outdated:
’’’
https://github.com/aquacash5/magic-wormhole-exe/releases/latest/download/wormhole.zip
’’’
and just use:
’’’
$packageName = 'magic-wormhole'
$fileType = 'exe'
$url = 'https://github.com/aquacash5/magic-wormhole-exe/releases/latest/download/wormhole.zip'
$silentArgs = '/S'

Install-ChocolateyPackage $packageName $fileType $silentArgs $url
’’’

or maybe better:
’’’
https://github.com/aquacash5/magic-wormhole-exe/releases/download/0.12.0/wormhole.zip
’’’
and automation:

’’’
https://github.com/majkinetor/au/blob/master/README.md
’’’


Maybe your zip could also contain version information if we need it, or each release on Chocolatey will use a versioned link. This is something I'd like to figure out later today.



’’’You can extract the application within the package directory itself (or even ship an extracted version with the package). This allows Chocolatey to automatically find executables and put those on %path%.’’’

At least the steps afterwards seem easy enough.

**Comment by vaporwave9** [comment]
Okaaaaaay, that was horrible but also easy.
I guess the chocolatey guys are geniusses with terrible communication.

Steps to bundle your package:
```
choco new magic-wormhole
```

Delete all inside that directory except:
```
magic-wormhole.nuspec
tools\bin\wormhole.exe
tools\LICENSE
tools\README
```
Use your favourite editor like Notepad++ and edit the ```.nuspec```

(I had no time this is super preliminary so bear with me, we hash it out and make a clear package together with icons and all.)

Inside the dir with your ```.nuspec``` you run:
```choco pack magic-wormhole.nuspec```
And you receive a ```magic-wormhole.0.12.0.nupkg``` which you can install or remove like:

```choco install magic-wormhole -dv -s .```
or
```choco uninstall magic-wormhole -dv -s .```

![grafik](https://user-images.githubusercontent.com/64961250/108621683-6cf44000-7434-11eb-8251-5cabb40adf67.png)

[magic-wormhole.zip](https://github.com/magic-wormhole/magic-wormhole/files/6017494/magic-wormhole.zip)

[magic-wormhole.0.12.0.nupkg.zip](https://github.com/magic-wormhole/magic-wormhole/files/6017495/magic-wormhole.0.12.0.nupkg.zip)

Artifacts for testing.

**Comment by aquacash5** [comment]
Sorry this is on my phone

I'm going to be gone most of the day, but I can make a change when I get back, so that the release has the raw executable and not the just zip. I can also include checksums document.

For the version information, I I don't think we need a special file with it because you can just query the program for it with `wormhole.exe --version`. Other than that I am using the same version as `magic-wormhole` in pypi. Alternatively, you can get the latest version using the GitHub api. There is an example of both in my `build-check.py` script. Though those are only useful if we are automating the chocolatey process.

**Comment by vaporwave9** [comment]
It might not be required anymore, as with each new build we can just update the version number in ```.nuspec``` run a oneliner to package and run a oneliner to push to the Community Package Repository in a fashion of ```choco push magic-wormhole.portable``` .

I chose to believe that at the current release speed a small ```.ps1``` script to change version number, build and push will be fine for now. Once we got it hosted and feel comfortable enough to automate I'll look into the steps.

https://docs.chocolatey.org/en-us/create/commands/push
This requires an API key and registering https://push.chocolatey.org/account

Do you also want to be package maintainer of Chocolatey.org or should I get it online? Negligible more work for you, at the benefit if I am on holidays you can update both the binary and the other repo.

**Comment by aquacash5** [comment]
Just wanted to update this thread.

https://chocolatey.org/packages/magic-wormhole.portable/0.12.0

All automated checks have passed. Just waiting for a manual review.

**Comment by aquacash5** [comment]
Everything is approved!

https://community.chocolatey.org/packages/magic-wormhole/0.12.0
