### ISSUE TITLE
Requires Python and Rust?

### ISSUE THREAD

**Issue by mn113** [magic-wormhole/magic-wormhole#409]
I ran `brew install magic-wormhole` on my Mac and it spent half an hour installing python 3.9 _and_ rust, which frankly seems out of order and puts me off waiting for this process to finish. Why is this?

```
$ brew info magic-wormhole
magic-wormhole: stable 0.12.0
Securely transfers data between computers
https://github.com/warner/magic-wormhole
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/magic-wormhole.rb
License: MIT
==> Dependencies
Build: rust ✘
Required: libsodium ✘, openssl@1.1 ✔, python@3.9 ✔
```

**Comment by piegamesde** [comment]
I'm pretty confident that the the python implementation requires neither Rust nor Ruby. Please ask the downstream packagers what is happening here.

**Comment by meejah** [comment]
i think it's probably (more) fallout from `cryptography` (a dependency of magic-wormhole) now requiring Rust: https://cryptography.io/en/latest/faq.html?highlight=rust#installing-cryptography-fails-with-error-can-not-find-rust-compiler

**Comment by meejah** [comment]
I'm closing this because I don't believe there's anything this project can do; `cryptography` should be shipping wheels for all platforms -- only source installs would require Rust then. If there *is* something this project can do, please re-open.
