### ISSUE TITLE
Error: No space left on device

### ISSUE THREAD

**Issue by MukundVarmaT** [magic-wormhole/magic-wormhole#413]
When running `wormhole send <file>`, I get the following error.

```
ERROR: We had a problem connecting to the relay server:
(relay URL was ws://relay.magic-wormhole.io:4000/v1)
connection was closed uncleanly (WebSocket connection upgrade failed (500 - Internalservererror [Errno28]Nospaceleftondevice))
```

**Comment by SquareManRan** [comment]
Not sure if this is the fix, but I was having the same issue until I switched my cmd's directory. Worked fine after one switch and even worked when back in the default directory. Again, not positive that is what fixed it but it might be worth trying.

**Comment by MukundVarmaT** [comment]
I think the issue is solved now! Anyways I will leave this open in case it's of some use/reference for the collaborators!

**Comment by peterbabic** [comment]
It is happening again, three separate devices on different part of the internet report the same:

```
ERROR: We had a problem connecting to the relay server:
(relay URL was ws://relay.magic-wormhole.io:4000/v1)
connection was closed uncleanly (WebSocket connection upgrade failed (500 - Internalservererror:[Errno28]Nospaceleftondevice))
```

**Comment by rmnijgh** [comment]
Same thing over here ^^
