### ISSUE TITLE
ERROR: We had a problem connecting to the relay server:

### ISSUE THREAD

**Issue by SquareManRan** [magic-wormhole/magic-wormhole#414]
Hello, this is my first issue submission on Github, and I am a bit new to this so please forgive any awkwardness. I looked at the solved issues and saw none fitting my error and none matching mine in the open. 

I started using wormhole yesterday as a method of sending files to and from a server machine that I manage at a friend's house, and it worked beautifully. However, today I went to use it again just to mess around, and it gives me this error:

`ERROR: We had a problem connecting to the relay server:
(relay URL was ws://relay.magic-wormhole.io:4000/v1)
connection was closed uncleanly (WebSocket connection upgrade failed (500 - Internalservererror:[Errno28]Nospaceleftondevice))`

I am not sure if this is an issue on my end or the relay server's end, but the command used to receive this error was simply `wormhole send` I see a code: `Nospaceleftondevice` in the error, but I have plenty of space.

Any help is appreciated, no matter how small. Thanks - SquareManRan

**Comment by piegamesde** [comment]
Duplicate of #413

**Comment by SquareManRan** [comment]
> Duplicate of #413

Apologies, I'll close this one since the other is also open to keep clutter down.
