### ISSUE TITLE
Stuck on "Waiting for Wormhole Network consensus..."

### ISSUE THREAD

**Issue by marmijo505** [magic-wormhole/magic-wormhole#425]
Hello, I have been stuck on the "Waiting for Wormhole Network consensus..." status for a while now. Step 3 looks to have succeeded with transaction https://explorer.solana.com/tx/iZbQHn3UnYXRrvxpUyy8oGkeAprC7ocXp4W19GwFhK8kmBVsw2RjederLVkJ1jD3PKt1yU7ojp5qzKkERsgNm2n

How can I move the process along to step 4?

**Comment by meejah** [comment]
This doesn't appear to have anything to do with our project.
