### ISSUE TITLE
Average time estimates

### ISSUE THREAD

**Issue by xeruf** [magic-wormhole/magic-wormhole#430]
The time estimate for transfer time remaining should average the recent speed (maybe of the last minute) so it does not jump around erratically and becomes more realistic and useful.

But thanks for the great tool already!

**Comment by warner** [comment]
We delegate all of this tracking to the generally-excellent `tqdm` library (https://github.com/tqdm/tqdm). I don't know exactly how they do their estimation, but https://github.com/tqdm/tqdm#parameters says the `smoothing=` parameter uses an exponential decay algorithm, which would pay more attention to recent activity than older activity. That sounds a lot like what you want, although it wouldn't cut off at just the last 60s.

I haven't observed the time estimate jumping around a lot, but I know that depends a huge amount on the behavior of your network on any given day.

You might play around with changing our call to `tqdm()` in `src/wormhole/cli/cmd_receive.py` and `cmd_send.py`, and add a `smoothing=1.0` or `smoothing=0.0` or something in between. If I'm reading the docs correctly, `0.0` would average over the whole lifetime of the connection, so it would be maximally stable. While `1.0` would look only at the most recent sample, so it would be maximally jumpy (but would also ignore old data, so in some sense it would be maximally accurate).

I want to avoid rewriting this algorithm locally.. I like having `tqdm` own the estimation process, and I'm willing to believe that they have a better intuition for what the default `smoothing=` value should be than me. So I think I'm going to close this as a WONTFIX: I don't think we can do better than the status quo.

Thanks for using magic wormhole!

**Comment by xeruf** [comment]
Yes, the smoothing sounds perfect - though it says there that the default is 0.3, which does not match my experience, hm...
