### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [magic-wormhole/magic-wormhole#439]
As it seems you support older pythons, I guess it is not possible to replace mock usage by unittest.mock, but perhaps you could consider to use unittest.mock as a fallback, when mock is not present?

Same eventually for magic-wormhole-transit-relay and magic-wormhole-mailbox-server at least.

Background:
https://trello.com/c/S6eADbii/64-remove-python-mock
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

**Comment by alerque** [comment]
This should get addressed. I see some commits linked there that suggest SUSE is having to patch this. Also [Fedora](https://fedoraproject.org/wiki/Changes/DeprecatePythonMock) and [Arch Linux](https://archlinux.org/todo/drop-python-mock-checkdepends/) are faced with this being deprecated and needing to patch it out of upstreams that don't fix it themselves.

Please save downstream packages some pain and just switch. If you must have a fallback the fallback should be to support the older system, not the current one.

**Comment by meejah** [comment]
Yes, agree -- I only want to support Python 3 going forward so would accept a PR to simply use the built-in mock (for this and the server repos).

**Comment by alerque** [comment]
Somebody already did this for this repo and also for transit-relay. I just submitted a Pr for mailbox-server. That should be a wrap.
