### ISSUE TITLE
Allow Wormhole code to be custom too

### ISSUE THREAD

**Issue by domino2** [magic-wormhole/magic-wormhole#441]
Wouldn't be nice to be able to set the Wormhole code by cli param?
Files I want to send doesn't need to be secured and to be faster on the server I may press just arrow up and hit the enter.

Well I presuming it is not there as I didn't see it in the help and quick google search.

**Comment by meejah** [comment]
It is there (``--code`` on send and an argument on receive).

**Comment by domino2** [comment]
Great, but it is not printed in the help output `wormhole --help`. I have magic-wormhole `0.12.0` on macos `12.5.1` installed through brew.

**Comment by meejah** [comment]
`wormhole send --help` or `wormhole receive --help` should give you what you need..
