### ISSUE TITLE
when trying to install via zypper: Package 'python-magic-wormhole' not found.

### ISSUE THREAD

**Issue by mashakos** [magic-wormhole/magic-wormhole#472]
I cant install wormhole via zypper on my openuse 15.4 server

ERROR is
"Package 'python-magic-wormhole' not found."

occurs with 
sudo zypper install python-magic-wormhole
OR
sudo zypper addrepo https://download.opensuse.org/repositories/devel:languages:python:backports/15.4/devel:languages:python:backports.repo
sudo zypper refresh
sudo zypper install python-magic-wormhole

**Comment by meejah** [comment]
Sounds like a problem with the distribution, please inquire there. (Or, if you think there's something to be done by this project, please say what..)
