### ISSUE TITLE
Is it possible to set password, to automate the send and receive?

### ISSUE THREAD

**Issue by aviezab** [magic-wormhole/magic-wormhole#475]
Hi,
I have a case that I want to running magic-wormhole in crontab so the app can run periodically without inputting password on receiver computer.

Could You guys help? Thanks.

**Comment by meejah** [comment]
I think this is a use-case for Seeds (#77 and https://github.com/magic-wormhole/magic-wormhole-protocols/issues/2 )

For this use-case, it would mean: setting up a Seed with that machine once (e.g. by doing a send or receive with a human-entered code) and then using the Seed periodically after that (which means not having to enter a code anymore, between the same two machines).

Note that Seeds are _not_ yet implemented in any client.

**Comment by aviezab** [comment]
@meejah Thanks for the reply.
so right now is not implemented yet to use.

I know this is dangerous if somebody has the same password, but I am sure in the future this feature helps many users.
