### ISSUE TITLE
feature request: shell completion for subcommands

### ISSUE THREAD

**Issue by j-lakeman** [magic-wormhole/magic-wormhole#498]
I really appreciate the existing command completion for the wormhole codes!
IMHO it would be also quite handy to have a completion for "subcommands" like `send`, `receive`, etc. Restic https://github.com/restic/restic/ also does this and I really appreciate the feature as it speeds up typing a lot.
One could type `wormhole r` + TAB and `receive` could be autocompleted.

**Comment by meejah** [comment]
Since we're using Click for the CLI stuff this is somewhat straightforward it turns out!

See if the instructions work for you :) (note you'll have to download the completions file from the branch itself).

**Comment by j-lakeman** [comment]
Yep, seems to work, great!
Is it much effort to add support for zsh and fish as well?

**Comment by meejah** [comment]
Yeah, it supports those two as well -- added, and updated docs + release process.
