### ISSUE TITLE
test_large_frame failing

### ISSUE THREAD

**Issue by mweinelt** [magic-wormhole/magic-wormhole#500]
We (nixpkgs) are currently in a large python package set upgrade, and I'm seeing the following test for magic-wormhole 0.13.0 fail. I've ruled out the twisted 23.8.0 update so far, and I'm not exactly sure what dependency could cause this error.

```python
___________________________ Record.test_large_frame ____________________________

self = <wormhole.test.dilate.test_record.Record testMethod=test_large_frame>

    def test_large_frame(self):
        """
        Noise only allows 64KiB message, but the API allows up to 4GiB
        frames
        """
        # XXX could really benefit from some Hypothesis style
        # exploration of more cases .. but we don't already depend on
        # that library, so a future improvement
    
        @implementer(ITransport)
        class FakeTransport:
            """
            Record which write()s happen
            """
            def __init__(self):
                self.data = []  # list of bytes
    
            def write(self, data):
                self.data.append(data)
    
        # we build both sides of a connection so that underlying Noise
        # structures can be set up and paired properly. Essentially
        # this test is acting like the L2 Protocol object, and can
        # feed bytes to / from either side
        pake_secret = b"\x00" * 32
        transport0 = FakeTransport()
        transport1 = FakeTransport()
>       noise0 = build_noise()

src/wormhole/test/dilate/test_record.py:307: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def build_noise():
>       return NoiseConnection.from_name(NOISEPROTO)
E       AttributeError: 'NoneType' object has no attribute 'from_name'

src/wormhole/_dilation/connector.py:45: AttributeError
```

**Comment by meejah** [comment]
Looks like probably "Noise" isn't installed?

As Dilation is still experimental/optional, you'd install with `pip install magic-wormhole[dilate]` to get it (i.e. "install the `dilate` extra") as I assume Nix isn't using pip here (see https://github.com/magic-wormhole/magic-wormhole/blob/master/setup.py#L63C23-L63C36 )

(I don't know what https://github.com/magic-wormhole/magic-wormhole/blob/master/src/wormhole/_dilation/_noise.py#L19 means about 2.7 imports but also we don't support python2 anymore).

**Comment by meejah** [comment]
Probably the tests themselves could/should detect this and not run when dilation dependencies are not installed

**Comment by meejah** [comment]
An immediate solution for Nix could simply be to declare a dependency on `noiseprotocol` (the python library).

I don't know if / how Nix deals with Python extras?

**Comment by mweinelt** [comment]
Passing `noiseprotocol` in fixes the tests. Now I wonder where this had been coming from before.

`twisted[tls]`  on 23.8.0 provides `idna`, `pyopenssl` and `service-identity`.
`autobahn[twisted]`  23.6.2 provides `attrs`, `zope_interface` and `twisted` itself.

**Comment by mweinelt** [comment]
So clearly an issue on our end, we missed the `dilation` extra. Thanks for the pointers!
