### ISSUE TITLE
When sending a shallow folder of compressed media, use a non deflated zip file (compression level 0)

### ISSUE THREAD

**Issue by zackees** [magic-wormhole/magic-wormhole#523]
Often I am sending media from one computer to another.

`magic-wormhole` will compress this high entropy media content and this will take a long time for almost no beneift.

It would be awesome if a simple heuristic could be used to detect this use case and set the compression level to 0 (no compression, just store it as one file).

Here's some pseudocode for such a hueristic

```
COMPRESSION_LEVEL=9

files = os.list(target_directory)
if len(files) < 250:
  if greater than 90% of directory bytes comes from media files:
    COMPRESSION_LEVEL=0
```

**Comment by zackees** [comment]
Just did a test on 28 GB worth of media content.

5 mins was spent compressing the files and 37 mins was spent sending the file.

So even if this improves the high entropy case, the likely hood it will have significant is almost non existant.

**Comment by pR0Ps** [comment]
Note that as of v0.14.0 (specifically #503) no compression will be used for the zip file and it's created on the fly so there should be almost no startup time.
