### ISSUE TITLE
Error "-bash: complete: nosort: invalid option name" on macOS, possibly due to bash version

### ISSUE THREAD

**Issue by RobertoD91** [magic-wormhole/magic-wormhole#524]
Installed magic-wormhole on macos with homebrew:
`brew install magic-wormhole`

If bash is the default shell, the error "-bash: complete: nosort: invalid option name" appears at terminal startup.

This issue seems to be caused by the `-o nosort` option in https://github.com/magic-wormhole/magic-wormhole/blob/241a8358ce8ec4e12fd393f562e9dbee6484eba9/wormhole_complete.bash#L25 located in `/usr/local/etc/bash_completion.d/wormhole.bash`

**Comment by RobertoD91** [comment]
Perhaps the issue arises because the default version of Bash on macOS is an outdated version 3. For instance:
```bash
$ /bin/bash --version # default macos bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin23)
(...)
```
Indeed, when using a more modern version of Bash, such as the one from Homebrew, the error does not occur:
```bash
$ /usr/local/bin/bash --version # bash installed with homebrew
GNU bash, versione 5.2.26(1)-release (x86_64-apple-darwin23.2.0)
(...)
```
so a possible fix will be:
```bash
_wormhole_completion_setup() {
    if [[ "${BASH_VERSINFO[0]}" -lt 4 ]]; then
        complete -F _wormhole_completion wormhole
    else
        complete -o nosort -F _wormhole_completion wormhole
    fi
}```

**Comment by meejah** [comment]
Happy to just merge that if you re-state it as a PR :)

I believe I was just following some other instructions when making the completions work, so I don't know why there's a `nosort` there at all
