### ISSUE TITLE
Outdated Dependencies / downstream help

### ISSUE THREAD

**Issue by meejah** [magic-wormhole/magic-wormhole#534]
(originally from @emilazy, in a comment): FWIW based on my own experience in Nixpkgs I’m guessing downstreams would be less hesitant about the maintenance status here if there wasn’t a dependency on a cryptography library (`spake2`) that hasn’t been touched in 6 years that depends on a cryptography library (`hkdf`) that hasn’t been touched in a decade. Pure algorithm implementations are maybe the least worrying kind of cryptography library to be completely unmaintained, but it’s still concerning, and nothing else in our large repository (other than optional dependencies on another library for a dead cryptocurrency project) depends on those libraries.

I don’t know if there are other Python implementations of SPAKE2 that could be used instead, though; I found a CFFI‐based binding to a C implementation but I don’t know if that’s really better.

Does the Magic Wormhole project consider the Rust version to be an adequate replacement for the Python one? (Asking in case things have changed since 2022.)

_Originally posted by @emilazy in https://github.com/magic-wormhole/magic-wormhole/issues/468#issuecomment-2255700005_

**Comment by meejah** [comment]
Opening a new issue here so that this problem can be tracked without referring to a closed issue ;)

The `hkdf` library is old and not-very-maintained; it has an equivalent in "cryptography" and even a PR (https://github.com/warner/python-spake2/pull/14) to upgrade to that. This will eliminate the "hkdf" dependency from `python-spake2` and hence also `magic-wormhole`

The `python-spake2` library hasn't had a recent release, making downstream packagers nervous (understandable). More practically, it has some issues with Python 3.12 (and also a PR https://github.com/warner/python-spake2/pull/14).

So the high-level "issue" here is that `python-spake2` needs some love and a release. Or, even more generally, "some of magic-wormhole dependencies are old and/or unloved".

**Comment by meejah** [comment]
the HKDF library is now no longer a dependency, and release `v0.9` has this change in it.

**Comment by meejah** [comment]
Oops. Keeping this open because we need a magic-wormhole release that depends on python-spake v0.9

**Comment by emilazy** [comment]
Hoping for a release soon if possible as we’re coming to the end of our own release development cycle :)

**Comment by meejah** [comment]
Thanks for the bump, 0.16.0 is released: https://github.com/magic-wormhole/magic-wormhole/releases/tag/0.16.0 and https://pypi.org/project/magic-wormhole/0.16.0/

**Comment by emilazy** [comment]
Thank you! From the NixOS end I think we can consider this totally resolved now.
