### ISSUE TITLE
A bunch of tests fail with magic-wormhole-transit-relay 0.3.1

### ISSUE THREAD

**Issue by triallax** [magic-wormhole/magic-wormhole#543]
while bumping magic-wormhole-transit-relay for chimera linux, i got a bunch of tests failing:
https://gist.github.com/triallax/efa7da4248ab6017dedbb7a56d2282ba

would be nice if we can get those fixed :)

**Comment by meejah** [comment]
Could you please file this against https://github.com/magic-wormhole/magic-wormhole-transit-relay/ instead, and say some more about the setup if it seems relevant? (I can move if you want, but then I'll "own" the ticket).

At a first glance, it seems like these could be related to python 3.12 ...?

**Comment by triallax** [comment]
i don't mind refiling it there, but is that really correct? these test failures are from magic-wormhole's test, i mentioned the transit relay thing specifically because these failures only occur after the bump, everything passes fine with magic-wormhole-test-relay 0.2.1

**Comment by meejah** [comment]
Ahh, sorry I guess my glance was _too_ brief, I didn't grok that it's _this_ test-suite failing. thanks

**Comment by triallax** [comment]
no worries, i did make the issue body unnecessarily terse and unclear (i didn't explicitly state it was magic-wormhole's test suite even)

**Comment by meejah** [comment]
Cannot repeat with Python 3.11 and magic-wormhole-transit-relay 0.3.1

(Will try with Python 3.12)

**Comment by meejah** [comment]
Hmm, works for me with 3.12.1 as well:

```
PASSED (successes=456)
  py312: OK (67.27=setup[21.19]+cmd[0.88,0.65,44.55] seconds)
  congratulations :) (68.63 seconds)
```

**Comment by meejah** [comment]
Arg, my bad. Tox had pinned an older version of magic-wormhole-transit relay.

I have repeated with 3.12.7 and 0.3.1. Thanks for the report!

**Comment by meejah** [comment]
Would be good to know if the proposed PR fixes things in your setup as well (let me know if you need help installing via `pip` + `git`)

**Comment by satta** [comment]
Works for me as well, also updated in Debian packaging. Thanks!
