### ISSUE TITLE
Please tag a release for test fixes

### ISSUE THREAD

**Issue by satta** [magic-wormhole/magic-wormhole#548]
Could you maybe please consider tagging a release that includes the test fixes from #543? These break package builds in Debian right now (as transit-relay in Debian was updated to 0.3.1, breaking tests in magic-wormhole itself) and it would be better to reference a new upstream version instead of including https://github.com/magic-wormhole/magic-wormhole/commit/060a62bed3e76b54f8f94e7f45ce2c02225afd57.patch as a patch.

Thanks!

**Comment by meejah** [comment]
https://pypi.org/project/magic-wormhole/0.17.0/

**Comment by satta** [comment]
Thanks!
