### ISSUE TITLE
Wormhole Seeds

### ISSUE THREAD

**Issue by warner** [magic-wormhole/magic-wormhole#77]
As mentioned in #76, "Wormhole Seeds" are an API/protocol feature that could enable convenient re-use of connections established by a normal short-code -based Wormhole.

Basically, both sides of a Wormhole connection would derive a 128-bit mailbox-id and a 256-bit wormhole secret (from the PAKE session key), and store it for later use as a "Seed". This seed is used exactly like a normal wormhole code, except that the mailbox ID is used directly (instead of being treated as a "nameplate" which then points to a mailbox), and the Seed can be reused.

(we don't strictly need to use PAKE each time, but it happens to provide forward-secrecy, and we already have all the code in place.. it'd actually be _more_ work to use a simple non-PAKE KDF).

(also, the wormhole secret could be considerably shorter, and still be safe, but there's no harm in making it full-sized)

The API I'm thinking of would be like:

``` python
w = wormhole.create(stuff)
w.set_code(code)
w.connect() # ...
seed = w.get_seed()

# later
w = wormhole.from_seed(seed)
w.connect()
```

**Comment by meejah** [comment]
Please see https://github.com/magic-wormhole/magic-wormhole-protocols/issues/2 instead.
